In [82]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('dataset.csv')
df.head()

,Title,People_Review,Selling_Price,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100 Ratings,Rs. 300,Free,98%,97%,Not Found,Not Found,100%
1,thik grow and rich#rich dad poor dad,61 Ratings,Rs. 400,Free,82%,100%,-55%,Rs. 895,86%
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113 Ratings,Rs. 628,Rs. 99,80%,100%,-58%,"Rs. 1,500",97%
3,The Silent Patient Novel by Alex Michaelides,43 Ratings,Rs. 250,Free,81%,100%,-75%,Rs. 999,100%
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238 Ratings,Rs. 899,Free,87%,100%,-80%,"Rs. 4,499",100%

In [83]:
df = df[['Title', 'People_Review', 'Deliver_Charges', 'Seller_Rating', 'Shipping_Timing_Rating', 'Discount_Percentage', 'Selling_Price', 'Original_Price', 'Chat_Responce_Rate']]
df.head()

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100 Ratings,Free,98%,97%,Not Found,Rs. 300,Not Found,100%
1,thik grow and rich#rich dad poor dad,61 Ratings,Free,82%,100%,-55%,Rs. 400,Rs. 895,86%
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113 Ratings,Rs. 99,80%,100%,-58%,Rs. 628,"Rs. 1,500",97%
3,The Silent Patient Novel by Alex Michaelides,43 Ratings,Free,81%,100%,-75%,Rs. 250,Rs. 999,100%
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238 Ratings,Free,87%,100%,-80%,Rs. 899,"Rs. 4,499",100%

In [84]:
df = df.replace({'Deliver_Charges': {'Free':np.NaN}})
df = df.replace({'Discount_Percentage': {'Not Found':np.NaN}})
df = df.replace({'Original_Price': {'Not Found':np.NaN}})
df.head()

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100 Ratings,NaN,98%,97%,NaN,Rs. 300,NaN,100%
1,thik grow and rich#rich dad poor dad,61 Ratings,NaN,82%,100%,-55%,Rs. 400,Rs. 895,86%
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113 Ratings,Rs. 99,80%,100%,-58%,Rs. 628,"Rs. 1,500",97%
3,The Silent Patient Novel by Alex Michaelides,43 Ratings,NaN,81%,100%,-75%,Rs. 250,Rs. 999,100%
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238 Ratings,NaN,87%,100%,-80%,Rs. 899,"Rs. 4,499",100%

In [85]:
# Removing digits and special characters from the digits values
df['People_Review'] = df['People_Review'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Selling_Price'] = df['Selling_Price'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Seller_Rating'] = df['Seller_Rating'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Shipping_Timing_Rating'] = df['Shipping_Timing_Rating'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Chat_Responce_Rate'] = df['Chat_Responce_Rate'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Deliver_Charges'] = df['Deliver_Charges'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Discount_Percentage'] = df['Discount_Percentage'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\-\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df['Original_Price'] = df['Original_Price'].str.replace(r'[a-zA-Z!@#$%^&*()_+={}\[\]:;"\'<>,.?/\\|`~]', '', regex=True)
df.head(15)

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100,NaN,98,97,NaN,300,NaN,100
1,thik grow and rich#rich dad poor dad,61,NaN,82,100,55,400,895,86
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113,99,80,100,58,628,1500,97
3,The Silent Patient Novel by Alex Michaelides,43,NaN,81,100,75,250,999,100
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238,NaN,87,100,80,899,4499,100
5,twisted #book1 love #2 game#3 hate#4lies combo...,12,NaN,88,100,NaN,1045,NaN,88
6,(Cat and Mouse Duet ) Haunting Adeline / _Hunt...,138,99,89,100,11,979,1099,98
7,The 48 Laws of Power by Robert Greene,93,99,91,100,17,499,599,91
8,Beyond the Story: 10-Year Record of BTS Book b...,65,99,89,100,35,587,899,98
9,The Psychology of Money by Morgan Housel,135,NaN,87,100,81,329,1699,100
10,verity by Colleen Hoover,108,NaN,88,100,12,199,225,88
11,the psychology of money,39,NaN,82,100,75,225,895,86
12,it startswith us #it ends withus by Colleen Ho...,13,NaN,82,100,67,410,1245,86
13,Yaaram Yaram Complete Novel by Sumaira Hameed ...,35,NaN,87,100,55,809,1799,100
14,it end with us by Collen hover,86,NaN,88,100,NaN,199,NaN,88

## EDA

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4081 entries, 0 to 4080
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   4080 non-null   object
 1   People_Review           4081 non-null   object
 2   Deliver_Charges         714 non-null    object
 3   Seller_Rating           4081 non-null   object
 4   Shipping_Timing_Rating  4081 non-null   object
 5   Discount_Percentage     3763 non-null   object
 6   Selling_Price           4081 non-null   object
 7   Original_Price          3763 non-null   object
 8   Chat_Responce_Rate      4080 non-null   object
dtypes: object(9)
memory usage: 287.1+ KB

In [88]:
df.describe()

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
count,4080,4081,714,4081,4081,3763,4081,3763,4080
unique,1574,146,10,27,24,83,407,164,30
top,Not Found,,99,87,100,1,299,1999,100
freq,38,1694,457,858,2812,327,221,560,2145

In [89]:
df = df.replace({'Title': {'Not Found':np.NaN}})

In [90]:
df['Title'].isna().sum()

39

In [92]:
df.isna().sum()

Title                       39
People_Review                0
Deliver_Charges           3367
Seller_Rating                0
Shipping_Timing_Rating       0
Discount_Percentage        318
Selling_Price                0
Original_Price             318
Chat_Responce_Rate           1
dtype: int64

In [93]:
df.head()

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100,NaN,98,97,NaN,300,NaN,100
1,thik grow and rich#rich dad poor dad,61,NaN,82,100,55,400,895,86
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113,99,80,100,58,628,1500,97
3,The Silent Patient Novel by Alex Michaelides,43,NaN,81,100,75,250,999,100
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238,NaN,87,100,80,899,4499,100

In [94]:
df = df.transpose()
df.head(30)

,0,1,2,3,4,5,6,7,8,9,...,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080
Title,World Times The Political World Map Edited by ...,thik grow and rich#rich dad poor dad,Peer e Kamil By umer Ahmed Best Selling Urdu Book,The Silent Patient Novel by Alex Michaelides,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",twisted #book1 love #2 game#3 hate#4lies combo...,(Cat and Mouse Duet ) Haunting Adeline / _Hunt...,The 48 Laws of Power by Robert Greene,Beyond the Story: 10-Year Record of BTS Book b...,The Psychology of Money by Morgan Housel,...,The Forty Rules of Love by Elif Shafak Urdu Ed...,You Can Become The Person You Want to be by Dr...,The power of your subconscious mind,The Prince by Niccolo Machiavelli Urdu Edition,Simple Trading Book I Simple Trading Book,The Laws of Human Nature By Robert Greene,Haraf Haraf Haqeeqat Urdu Book By Wasif Ali Wasif,Shayad By Jon Elia in urdu Poetry Book Best Se...,Simple Trading Book(Novel Size),Abraham Lincoln a Book By Sterling North Urdu ...
People_Review,100,61,113,43,238,12,138,93,65,135,...,63,53,412,5,4,6,3,465,4,
Deliver_Charges,NaN,NaN,99,NaN,NaN,NaN,99,99,99,NaN,...,NaN,NaN,119,NaN,99,NaN,NaN,NaN,NaN,NaN
Seller_Rating,98,82,80,81,87,88,89,91,89,87,...,98,98,96,98,89,87,98,89,,98
Shipping_Timing_Rating,97,100,100,100,100,100,100,100,100,100,...,98,98,100,98,100,100,98,98,100,98
Discount_Percentage,NaN,55,58,75,80,NaN,11,17,35,81,...,23,NaN,1,NaN,73,78,NaN,1,20,25
Selling_Price,300,400,628,250,899,1045,979,499,587,329,...,880,400,593,400,1348,445,500,395,682,300
Original_Price,NaN,895,1500,999,4499,NaN,1099,599,899,1699,...,1150,NaN,599,NaN,5000,1999,NaN,399,850,400
Chat_Responce_Rate,100,86,97,100,100,88,98,91,98,100,...,100,100,68,100,87,100,100,99,93,100

In [95]:
# Use a conditional statement to replace NaN values in the selected row with values from the row above
df.iloc[7] = df.iloc[6].where(df.iloc[7].isna(), df.iloc[7])
df.head(30)

,0,1,2,3,4,5,6,7,8,9,...,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080
Title,World Times The Political World Map Edited by ...,thik grow and rich#rich dad poor dad,Peer e Kamil By umer Ahmed Best Selling Urdu Book,The Silent Patient Novel by Alex Michaelides,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",twisted #book1 love #2 game#3 hate#4lies combo...,(Cat and Mouse Duet ) Haunting Adeline / _Hunt...,The 48 Laws of Power by Robert Greene,Beyond the Story: 10-Year Record of BTS Book b...,The Psychology of Money by Morgan Housel,...,The Forty Rules of Love by Elif Shafak Urdu Ed...,You Can Become The Person You Want to be by Dr...,The power of your subconscious mind,The Prince by Niccolo Machiavelli Urdu Edition,Simple Trading Book I Simple Trading Book,The Laws of Human Nature By Robert Greene,Haraf Haraf Haqeeqat Urdu Book By Wasif Ali Wasif,Shayad By Jon Elia in urdu Poetry Book Best Se...,Simple Trading Book(Novel Size),Abraham Lincoln a Book By Sterling North Urdu ...
People_Review,100,61,113,43,238,12,138,93,65,135,...,63,53,412,5,4,6,3,465,4,
Deliver_Charges,NaN,NaN,99,NaN,NaN,NaN,99,99,99,NaN,...,NaN,NaN,119,NaN,99,NaN,NaN,NaN,NaN,NaN
Seller_Rating,98,82,80,81,87,88,89,91,89,87,...,98,98,96,98,89,87,98,89,,98
Shipping_Timing_Rating,97,100,100,100,100,100,100,100,100,100,...,98,98,100,98,100,100,98,98,100,98
Discount_Percentage,NaN,55,58,75,80,NaN,11,17,35,81,...,23,NaN,1,NaN,73,78,NaN,1,20,25
Selling_Price,300,400,628,250,899,1045,979,499,587,329,...,880,400,593,400,1348,445,500,395,682,300
Original_Price,300,895,1500,999,4499,1045,1099,599,899,1699,...,1150,400,599,400,5000,1999,500,399,850,400
Chat_Responce_Rate,100,86,97,100,100,88,98,91,98,100,...,100,100,68,100,87,100,100,99,93,100

In [98]:
df = df.transpose()
df.head(30)

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Selling_Price,Original_Price,Chat_Responce_Rate
0,World Times The Political World Map Edited by ...,100,NaN,98,97,NaN,300,300,100
1,thik grow and rich#rich dad poor dad,61,NaN,82,100,55,400,895,86
2,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113,99,80,100,58,628,1500,97
3,The Silent Patient Novel by Alex Michaelides,43,NaN,81,100,75,250,999,100
4,"Rich Dad, Poor Dad / Atomic Habits /Think and ...",238,NaN,87,100,80,899,4499,100
5,twisted #book1 love #2 game#3 hate#4lies combo...,12,NaN,88,100,NaN,1045,1045,88
6,(Cat and Mouse Duet ) Haunting Adeline / _Hunt...,138,99,89,100,11,979,1099,98
7,The 48 Laws of Power by Robert Greene,93,99,91,100,17,499,599,91
8,Beyond the Story: 10-Year Record of BTS Book b...,65,99,89,100,35,587,899,98
9,The Psychology of Money by Morgan Housel,135,NaN,87,100,81,329,1699,100
10,verity by Colleen Hoover,108,NaN,88,100,12,199,225,88
11,the psychology of money,39,NaN,82,100,75,225,895,86
12,it startswith us #it ends withus by Colleen Ho...,13,NaN,82,100,67,410,1245,86
13,Yaaram Yaram Complete Novel by Sumaira Hameed ...,35,NaN,87,100,55,809,1799,100
14,it end with us by Collen hover,86,NaN,88,100,NaN,199,199,88
15,The Intelligent Investor Book by Benjamin Graham,40,NaN,87,100,74,517,1999,100
16,The Laws of Human Nature by Robert Greene,42,99,89,100,24,455,599,98
17,ugly love by Colleen hoover,25,NaN,82,100,31,275,399,86
18,it ends with us by Colleen Hoover,16,NaN,82,100,61,196,499,86
19,Peer e Kamil And Aab e Hayaat by umera Ahmed,95,159,80,100,50,1508,3000,97
20,The Art of Reading Minds by Henrik Fexeus,66,NaN,87,100,72,281,999,100
21,Peer E Kamil Urdu Book By Umera Ahmad,59,99,81,100,NaN,619,619,100
22,Haunting Adeline Book by H. D. Carlton,70,99,89,100,24,533,699,98
23,Atomic Habits by James Clear (Original),37,NaN,94,100,65,1395,3995,100
24,Mein Kampf Book by Adolf Hitler Urdu Edition,13,NaN,98,97,26,445,600,100
25,Allah_Loves by Omar Suleiman,86,NaN,87,100,79,375,1799,100
26,The 7 Habits of Highly Effective People by Ste...,67,NaN,87,100,72,277,995,100
27,NaN,,,,,NaN,,,
28,NaN,,,,,NaN,,,
29,"Fourth Wing (The Empyrean, #1) by Rebecca Yarros",6,99,89,100,24,528,699,98

## Train Test Split

In [103]:
y = df['Selling_Price']
X = df.drop('Selling_Price', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)
len(X_train), len(y_train), len(X_test), len(y_test)

(3264, 3264, 817, 817)

In [110]:
X_train.head(10)

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Original_Price,Chat_Responce_Rate
2173,The Seven Husbands of Evelyn Hugo Novel by Tay...,1,NaN,,91,56,899,100
2245,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113,99,80,100,58,1500,97
2367,Aab-E-Hayat urdu novel by Umera Ahmad Aab-E-Ha...,428,NaN,89,98,1,879,99
522,Reclaim Your Heart by Yasmin Mogahed,,NaN,87,100,81,1699,100
905,The Darkest Temptation,,NaN,86,100,70,999,92
2316,Master Your English – Direct Indirect Narratio...,3,NaN,94,100,2,440,100
1165,The 7 Habits Of Highly Effective People,1,NaN,91,78,50,599,95
1853,Hunting Adeline Novel by H. D. Carlton Best Se...,7,NaN,89,98,1,379,99
2606,Reclaim Your Heart by Yasmin Mogahed,,NaN,87,100,81,1699,100
1767,How to Stop Worrying and Start Living Book by ...,19,NaN,87,100,72,995,100

In [104]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3264 entries, 2173 to 3183
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   3230 non-null   object
 1   People_Review           3264 non-null   object
 2   Deliver_Charges         572 non-null    object
 3   Seller_Rating           3264 non-null   object
 4   Shipping_Timing_Rating  3264 non-null   object
 5   Discount_Percentage     3001 non-null   object
 6   Original_Price          3264 non-null   object
 7   Chat_Responce_Rate      3263 non-null   object
dtypes: object(8)
memory usage: 229.5+ KB

In [107]:
X_train = X_train.dropna(axis = 0, subset=['Title'], how='any')
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3230 entries, 2173 to 3183
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   3230 non-null   object
 1   People_Review           3230 non-null   object
 2   Deliver_Charges         541 non-null    object
 3   Seller_Rating           3230 non-null   object
 4   Shipping_Timing_Rating  3230 non-null   object
 5   Discount_Percentage     2997 non-null   object
 6   Original_Price          3230 non-null   object
 7   Chat_Responce_Rate      3230 non-null   object
dtypes: object(8)
memory usage: 227.1+ KB

In [108]:
X_train.head()

,Title,People_Review,Deliver_Charges,Seller_Rating,Shipping_Timing_Rating,Discount_Percentage,Original_Price,Chat_Responce_Rate
2173,The Seven Husbands of Evelyn Hugo Novel by Tay...,1,NaN,,91,56,899,100
2245,Peer e Kamil By umer Ahmed Best Selling Urdu Book,113,99,80,100,58,1500,97
2367,Aab-E-Hayat urdu novel by Umera Ahmad Aab-E-Ha...,428,NaN,89,98,1,879,99
522,Reclaim Your Heart by Yasmin Mogahed,,NaN,87,100,81,1699,100
905,The Darkest Temptation,,NaN,86,100,70,999,92

In [122]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
encoding_trans = Pipeline(steps=
                             [
                                 ('encode', OneHotEncoder(drop='first', sparse_output = False, dtype = np.int32))
                             ])
inputingDeCh = Pipeline(steps=
                    [
                        ('simpleImZaro', SimpleImputer(missing_values = np.nan, strategy='constant', fill_value=0))
                    ])
inputingPeRe = Pipeline(steps=[
                        ('simpleImMean', SimpleImputer(missing_values = np.nan, strategy = 'mean'))
                    ])

                    
col_trans = ColumnTransformer(transformer_weights=
                              [
                                ('Encoder', encoding_trans,[0]),
                                ('ImputerZero', imputingDeCh, [1, 2, 5]),
                                ('ImputeMean', imputingPeRe, [3,4,7])
                              ])
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('scaling', StandardScaler()),
                        ('regressor', LinearRegression())
                        ])
model.fit(X_train, y_train)

# Step 6: Make Predictions
y_pred = model.predict(X_test)
# Step 7: Evaluate the Model
# Coefficients and intercept
coefficients = model.coef_
intercept = model.intercept_

# Evaluation metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Coefficients: {coefficients}')
print(f'Intercept: {intercept}')
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

NameError: name 'imputingDeCh' is not defined